// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace crm.Backend.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

          


            modelBuilder.Entity("crm.Backend.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to")
                        .HasAnnotation("Relational:JsonPropertyName", "assignedTo");

                    b.Property<int?>("AssignedToCompany")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_to_company")
                        .HasAnnotation("Relational:JsonPropertyName", "assignedToCompany");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<DateTime?>("ExecutionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_date")
                        .HasAnnotation("Relational:JsonPropertyName", "executionDate");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location")
                        .HasAnnotation("Relational:JsonPropertyName", "location");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority")
                        .HasAnnotation("Relational:JsonPropertyName", "priority");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state")
                        .HasAnnotation("Relational:JsonPropertyName", "state");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title")
                        .HasAnnotation("Relational:JsonPropertyName", "title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("task", (string)null);
                });

#pragma warning restore 612, 618
        }
    }
}
